apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-2
spec:
  selector:
    matchLabels:
      app: app-2
  replicas: 1
  template:
    metadata:
      labels:
        app: app-2
    spec:
      containers:
      - name: app-2
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
        image: ealen/echo-server
        ports:
        - containerPort: 80
